# Your translations go here. To be used with the 'translate' liquid filter
# Example:
#   {{ 'hello_world' | translate }}
#

home_page:
  en: Home
  ja: ホーム

read_more:
  en: Read More
  ja: もっと見る

en:
  ja: English

ja:
  en: 日本語

posted_at_format:
  en: 'Posted at %-I:%M %p on %B, %-d %Y'
  ja: '%Y年%-m月%-d日 %H:%M'